version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html
    # networks:
    #   - laraxel
    depends_on:
      - postgres
      # - pgadmin
      # - redis
      # - redisInsight

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:latest
    build:
      context: .
      dockerfile: ./docker/config/db/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: /var/lib/postgresql/data/pgdata
    # networks:
    #   - laraxel
    # volumes:
    #   - ./docker/db/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:latest
    build:
      context: .
      dockerfile: ./docker/config/db/pgadmin/Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    # networks:
    #   - laraxel
    volumes:
      - ./docker/config/db/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/db/export:/var/lib/pgadmin/storage

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    # networks:
    #   - laraxel

  redisInsight:
    container_name: ${REDISINSIGHT_CONTAINER_NAME}
    image: redislabs/redisinsight:latest
    ports:
      - "${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT}"
    # networks:
    #   - laraxel
# networks:
#   laraxel:
#     driver: bridge
# volumes:
#   laraxel-app:
#     driver: local
# laraxel-postgres:
#   driver: local
# laraxel-pgadmin:
#   driver: local
