name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:



  phpstan-install:

    runs-on: ubuntu-latest

    steps:
    - name: Install phpstan
      run: composer install -d tools

  phpstan-run:

    runs-on: ubuntu-latest

    steps:
    - name: Run phpstan
      run: vendor/bin/phpstan
